//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Završi Zadatak.
        /// </summary>
        internal static string btnZavrsiText {
            get {
                return ResourceManager.GetString("btnZavrsiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prekini.
        /// </summary>
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Zadatak.
        /// </summary>
        internal static string DodajZadatakDetailsViewHeaderText {
            get {
                return ResourceManager.GetString("DodajZadatakDetailsViewHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo je do greške. Probajte ponovno..
        /// </summary>
        internal static string Greska {
            get {
                return ResourceManager.GetString("Greska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postoji neizvršen zadatak istog naziva..
        /// </summary>
        internal static string greskaPostojiZadatak {
            get {
                return ResourceManager.GetString("greskaPostojiZadatak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo je do greške pri brisanju podataka. Probajte ponovno..
        /// </summary>
        internal static string greskaPriBrisanjuPodataka {
            get {
                return ResourceManager.GetString("greskaPriBrisanjuPodataka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo je do greške pri dohvatu podataka. Probajte ponovno..
        /// </summary>
        internal static string greskaPriDohvatuPodataka {
            get {
                return ResourceManager.GetString("greskaPriDohvatuPodataka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo je do greške pri unosu podataka. Probajte ponovno..
        /// </summary>
        internal static string greskaPriUnosuPodataka {
            get {
                return ResourceManager.GetString("greskaPriUnosuPodataka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrvatski.
        /// </summary>
        internal static string imgButtonCroatiaText {
            get {
                return ResourceManager.GetString("imgButtonCroatiaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Njemački.
        /// </summary>
        internal static string imgButtonGermanyText {
            get {
                return ResourceManager.GetString("imgButtonGermanyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        internal static string imgButtonUKText {
            get {
                return ResourceManager.GetString("imgButtonUKText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        internal static string InsertButtonText {
            get {
                return ResourceManager.GetString("InsertButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat:.
        /// </summary>
        internal static string lblHourText {
            get {
                return ResourceManager.GetString("lblHourText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuta:.
        /// </summary>
        internal static string lblMinutesText {
            get {
                return ResourceManager.GetString("lblMinutesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nama.
        /// </summary>
        internal static string MasterPageLinkOnama {
            get {
                return ResourceManager.GetString("MasterPageLinkOnama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početna.
        /// </summary>
        internal static string MasterPageLinkPocetna {
            get {
                return ResourceManager.GetString("MasterPageLinkPocetna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaci Aplikacija.
        /// </summary>
        internal static string MasterPageTitleText {
            get {
                return ResourceManager.GetString("MasterPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naslov.
        /// </summary>
        internal static string NaslovHeaderText {
            get {
                return ResourceManager.GetString("NaslovHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naslov ne smije biti dulji od 50 znakova..
        /// </summary>
        internal static string NaslovLengthErrorMessage {
            get {
                return ResourceManager.GetString("NaslovLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naslov je obvezan..
        /// </summary>
        internal static string NaslovRequiredErrorMessage {
            get {
                return ResourceManager.GetString("NaslovRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        internal static string OpisHeaderText {
            get {
                return ResourceManager.GetString("OpisHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis ne smije biti dulji od 300 znakova..
        /// </summary>
        internal static string OpisLengthErrorMessage {
            get {
                return ResourceManager.GetString("OpisLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        internal static string OpisText {
            get {
                return ResourceManager.GetString("OpisText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početak.
        /// </summary>
        internal static string PocetakHeaderText {
            get {
                return ResourceManager.GetString("PocetakHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početak je obvezan..
        /// </summary>
        internal static string PocetakRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PocetakRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uredi.
        /// </summary>
        internal static string UpdateButtonText {
            get {
                return ResourceManager.GetString("UpdateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši.
        /// </summary>
        internal static string zadaciGridViewDeleteText {
            get {
                return ResourceManager.GetString("zadaciGridViewDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema zadataka..
        /// </summary>
        internal static string zadaciGridViewEmptyDataText {
            get {
                return ResourceManager.GetString("zadaciGridViewEmptyDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum Završetka.
        /// </summary>
        internal static string zadaciGridViewKrajText {
            get {
                return ResourceManager.GetString("zadaciGridViewKrajText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naslov.
        /// </summary>
        internal static string zadaciGridViewNaslovText {
            get {
                return ResourceManager.GetString("zadaciGridViewNaslovText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        internal static string zadaciGridViewOpisText {
            get {
                return ResourceManager.GetString("zadaciGridViewOpisText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi.
        /// </summary>
        internal static string zadaciGridViewSelectText {
            get {
                return ResourceManager.GetString("zadaciGridViewSelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum Početka.
        /// </summary>
        internal static string zadaciGridViewStartText {
            get {
                return ResourceManager.GetString("zadaciGridViewStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Završen.
        /// </summary>
        internal static string zadaciGridViewStatusText {
            get {
                return ResourceManager.GetString("zadaciGridViewStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadatak je već završen..
        /// </summary>
        internal static string zadatakZavrsenMessage {
            get {
                return ResourceManager.GetString("zadatakZavrsenMessage", resourceCulture);
            }
        }
    }
}
